// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrhvitfzgxlgftdchgkn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlyaHZpdGZ6Z3hsZ2Z0ZGNoZ2tuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3MzU2NjQsImV4cCI6MjA2NzMxMTY2NH0.U3YsycFDgvUyIWBnOGO5s46nYXciIqw79WqopaUSSUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});